name: flatconfig_example
description: Example for the flatconfig package.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flatconfig:
    path: ..

dev_dependencies:
  lints: ^6.0.0
