name: flatconfig
description: >
  Flat, human-friendly key=value configuration format for Dart & Flutter —
  inspired by Ghostty, simpler than INI or TOML.
version: 0.4.0

repository: https://github.com/grumpypixel/flatconfig
issue_tracker: https://github.com/grumpypixel/flatconfig/issues
homepage: https://github.com/grumpypixel/flatconfig

topics:
  - config
  - parser
  - keyvalue
  - ghostty
  - flat

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ">=1.16.0 <2.0.0"
  path: ^1.9.1

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
