name: flatconfig
description: >
  A minimal `key = value` configuration parser for Dart & Flutter —
  easy to read, supports duplicate keys, comments, and empty values as reset.
version: 0.1.4

repository: https://github.com/grumpypixel/flatconfig
issue_tracker: https://github.com/grumpypixel/flatconfig/issues
homepage: https://github.com/grumpypixel/flatconfig

topics:
  - config
  - flat
  - ghostty
  - keyvalue
  - parser

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ">=1.16.0 <2.0.0"
  path: ^1.9.1

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.26.3
